server:
  port: 8081
## docker JSB
#  port: 9090
#  
#  
keycloak:
#Standalone
#  auth-server-url: http://localhost:8180/auth
# Docker
  auth-server-url: http://localhost:8080
  realm: demo
  resource: springboot-keycloak
  public-client: true
  bearer-only: true